### ISSUE TITLE
standard unit list might be pulling from EML 2.2 list instead of 2.1.1

### ISSUE THREAD

**Issue by mobb** [PASTAplus/metadata-eml#10]
This editor creates EML 2.1.1
However, it looks to me like the standard unit list it is using is the one from EML 2.2.
Evidence: The drop down includes `milligramPerLiter` which is not in the 2.1.1 unit list (it was added for EML 2.2)
EML 2.1 has milligramsPerLiter (note the 's') which is valid 2.2, but deprecated in favor of the singular spelling.

**Comment by jon-ide** [comment]
We're doing EML 2.2, so this is ok.
