### ISSUE TITLE
alert user if the EML is invalid

### ISSUE THREAD

**Issue by mobb** [PASTAplus/metadata-eml#12]
I filled out the forms out-of-order. and forgot to add a contact. 
So the EML I downloaded was invalid (contact is required). For a data manager, it's conceivable they would want to download a doc that was in progress.

It doesn't make sense to see this alert all the time, but if the user is downloading the EML, the app could tell them that what they are downloading is not yet valid EML.

**Comment by jon-ide** [comment]
Done, via the "Check" feature.
