### ISSUE TITLE
Multi-paragraph text should have paragraph breaks

### ISSUE THREAD

**Issue by mobb** [PASTAplus/metadata-eml#18]
currently these are all in one `<para>` tag. they have line breaks, but of course, these get eaten up in processing.

**Comment by mobb** [comment]
Correction: 
- Abstract has no para tags at all
- methods has all text in one para.

treat them all the same.

**Comment by jon-ide** [comment]
For now, we're assuming the metadata editor is handling files it created. I.e., it doesn't expect to see a mix of sections and paras, just paras. Given that assumption, it's fixed.
