### ISSUE TITLE
access rules should not require that the user knows the whole LDAP entry

### ISSUE THREAD

**Issue by mobb** [PASTAplus/metadata-eml#19]
there is a single string form for adding the userID for an access rule. I am presuming the EML needs to have the full LDAP DN (the app created one for me when I logged in). 

but a user is not likely to know the DN, so the form should fill it out for them. Here is example of what I got in the EML when I added userID `edi`:

```xml
      <allow>
            <principal>uid=mobrien,o=EDI,dc=edirepository,dc=org</principal>
            <permission>all</permission>
        </allow>
        <allow>
            <principal>public</principal>
            <permission>read</permission>
        </allow>
        <allow>
            <principal>edi</principal>
            <permission>all</permission>
        </allow>
```

**Comment by jon-ide** [comment]
For now, we are hiding Access Rules in the metadata editor. Access will automatically be granted to the user who is logged in to the editor.

**Comment by servilla** [comment]
I believe we decided that "all" access should be granted to the metadata owner (the user who is logged in) and "read" access to the "public" user - is this correct?

**Comment by jon-ide** [comment]
I was wondering about that – read for public. Seems like a reasonable default.

**Comment by jon-ide** [comment]
I just checked… That is in fact what is written to the eml file.

    <access system="https://pasta.edirepository.org" scope="document" order="allowFirst" authSystem="https://pasta.edirepository.org/authentication">
        <allow>
            <principal>uid=EDI,o=EDI,dc=edirepository,dc=org</principal>
            <permission>all</permission>
        </allow>
        <allow>
            <principal>public</principal>
            <permission>read</permission>
        </allow>
    </access>

**Comment by jon-ide** [comment]
That is what’s currently done for the document as a whole.

There are also access rules for data tables and other entities. I take it I should do the same thing for them as well:  i.e., suppress “Add Access Rule” and automatically set the access as for the document.

**Comment by servilla** [comment]
I don't believe access rules were being applied at the data entity level (data table or other entity). The access rule that is applied at the the EML package level suffices since it also covers the data entities if not set explicitly.

**Comment by mobb** [comment]
IMO, a second set of access rules at the entity level isn't necessary for this application. the whole package can share the default.
