### ISSUE TITLE
Can't get past Publisher screen

### ISSUE THREAD

**Issue by vanderbi** [PASTAplus/metadata-eml#20]
This is the workflow that I experienced:

I enter a Contact, click “Back”, then click “next” and reach the Publisher screen.  I enter a Publisher and click “Back”.  It has returned to “Contacts”, and when I click “Next” here, it again wants me to add a Publisher.   This is where I got stuck last time.  I can’t get beyond the “Publisher” screen.

**Comment by jon-ide** [comment]
Fix in branch EML_2_2_0
