### ISSUE TITLE
feature request: a field to hold an ORCID id

### ISSUE THREAD

**Issue by mobb** [PASTAplus/metadata-eml#4]
we use orcid ids pretty regularly now.

**Comment by mobb** [comment]
> Per Mark's email: the use of the Orcid is one example for the userId field in responsible party.


Yes, sorry to be vague. But I think that orcid is the only id we are planning to support in this application, so it's probably fine to tailor the form to that.

**Comment by jon-ide** [comment]
Added a User ID field, but it needs a "directory" attribute. I'll need a list of allowable values to use.

**Comment by jon-ide** [comment]
ORCID ID field has been added. I.e., User ID is always ORCID ID, for now.
