### ISSUE TITLE
suggestions for geographicCoverage 

### ISSUE THREAD

**Issue by mobb** [PASTAplus/metadata-eml#6]
the display of geocov info is squished into narrow columns. This is OK for a single site, but hard to read if more than one. Suggest a table with these columns

text description (wider column, e.g. 50 char, not truncated)
north 
south
east
west

(the order should be the same as order they were requested in; see related issue #7)

**Comment by mobb** [comment]
related issue #7

**Comment by jon-ide** [comment]
Fix in branch EML_2_2_0
