### ISSUE TITLE
otherEntity forms tasks

### ISSUE THREAD

**Issue by mobb** [PASTAplus/metadata-eml#8]
The form defaults to an otherEntity that is a dataTable. So the form needs work to distinguish it from dataTable.
typical otherEntity uses are code, kml, zip files, and documents.

- [ ] remove attributeOrientation, recordDelims, etc. Even though the schema accommodates this, we do not want people to use otherEntity for tables, they should use dataTable instead.
- [ ] clarify what "entity type" means. are there choices? (I can't remember, will see what I can suss out and make a recommendation).

**Comment by mobb** [comment]
the editor will support only one format for otherEntity/dataFormat/externallyDefinedFormat 
Remove these fields:
Number of header lines
Record delimiter
Attribute Orientation
Simple Delimiter: Field Delimiter

@servilla  suspects that the code is assigning the content to a textFormat subtree, so check that this is not happening.

**Comment by jon-ide** [comment]
Removed fields as requested. Modified the code so it generates an externallyDefinedFormat subtree.
