### ISSUE TITLE
Suggestion: Move Edit menu to the left, always-on

### ISSUE THREAD

**Issue by mobb** [PASTAplus/metadata-eml#9]
A great place for the edit menu is over on the left in the margin. 
Ideally, it would always be open (rather than a dropdown), and the current form highlighted. 
That would give the user a sense of where they are in the process (and also highlight where the "Next" button is going to go), while still letting them jump around.

**Comment by mobb** [comment]
If it's not super difficult, highlight (or shade) the forms that have incomplete metadata. that might be better than encouraging people to use placeholders like "TO DO".

**Comment by jon-ide** [comment]
Done, except for the part about highlighting incomplete sections.

**Comment by jon-ide** [comment]
Done. Incomplete sections are found via the "Check" feature.
